#!/usr/bin/env python3
"""Build the interactive figures on research.qmd.

Reads  _scripts/figure-data/research-figures.json  (values traced from the
published papers' figures and tables; unpublished findings as shapes only)
and writes  _partials/research/fig-*.md , which research.qmd includes.

The figures are plain inline SVG plus a few data attributes; behavior lives in
assets/figures.js and styling in styles.scss (section "Interactive research
figures"). Nothing is fetched from another server.

Run by hand after changing the data or the drawing code:
    python3 _scripts/build_research_figures.py
"""
import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = json.load(open(os.path.join(ROOT, "_scripts", "figure-data", "research-figures.json"), encoding="utf-8"))
OUT = os.path.join(ROOT, "_partials", "research")

# Plot box shared by the small panels (viewBox 0 0 320 236).
X0, X1, Y0, Y1 = 46, 304, 26, 180
VB = "0 0 320 236"


def n1(v):
    return f"{v:.1f}"


def path(points):
    return "M" + " L".join(f"{x:.1f},{y:.1f}" for x, y in points)


def frange(a, b, steps):
    return [a + (b - a) * i / steps for i in range(steps + 1)]


def axes(x_title=None, y_title=None, x_title_y=226):
    out = [f'<line class="ax" x1="{X0}" y1="{Y1}" x2="{X1}" y2="{Y1}"/>',
           f'<line class="ax" x1="{X0}" y1="{Y0 - 6}" x2="{X0}" y2="{Y1}"/>']
    if y_title:
        out.append(f'<text class="ax-t" x="{X0}" y="{Y0 - 12}">{y_title}</text>')
    if x_title:
        out.append(f'<text class="ax-t" x="{X1}" y="{x_title_y}" text-anchor="end">{x_title}</text>')
    return out


def ytick(y, label):
    return (f'<line class="grid" x1="{X0}" y1="{n1(y)}" x2="{X1}" y2="{n1(y)}"/>'
            f'<text x="{X0 - 6}" y="{n1(y + 3.5)}" text-anchor="end">{label}</text>')


def xtick(x, label, y=Y1 + 14):
    return f'<text x="{n1(x)}" y="{y}" text-anchor="middle">{label}</text>'


def fmt(v, digits=2):
    s = f"{v:.{digits}f}"
    return s.replace("-", "−")


def write(name, html):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as fh:
        fh.write("<!-- Generated by _scripts/build_research_figures.py; edit that script, not this file. -->\n")
        fh.write("```{=html}\n" + html.strip() + "\n```\n")


def cite(key, label):
    return f'<a href="{D[key]["doi"]}">{label}</a>'


# ---------------------------------------------------------------------------
# Figure 1. Regulation as it unfolds
# ---------------------------------------------------------------------------
def fig_unfold():
    icd = D["icd2025"]
    C = icd["curves"]
    yr = {"distraction": (2.95, 3.09), "help": (3.13, 3.43), "venting": (3.46, 3.74)}
    color = {"distraction": "blue", "help": "amber", "venting": "red"}

    def xp(t):
        return X0 + (t + 10) / 20 * (X1 - X0)

    groups, scrub = [], []
    for s in ["distraction", "help", "venting"]:
        a, b, c = C[s]["a"], C[s]["b"], C[s]["c"]
        lo, hi = yr[s]

        def yp(v, lo=lo, hi=hi):
            return Y1 - (v - lo) / (hi - lo) * (Y1 - Y0)

        pts = [(xp(t), yp(a + b * (t + 10) + c * (t + 10) ** 2)) for t in frange(-10, 10, 80)]
        ticks = "".join(ytick(yp(v), f"{v:.2f}".rstrip("0").rstrip(".") if s != "distraction" else f"{v:.2f}") for v in icd["yticks"][s])
        groups.append(f'<g class="s-g s-{s}">{ticks}<path class="line {color[s]}" d="{path(pts)}"/></g>')
        scrub.append(f'data-coef-{s}="{a},{b},{c},{lo},{hi}"')

    xt = "".join(xtick(xp(t), ("−" if t < 0 else "") + str(abs(t))) for t in [-10, -5, 0, 5, 10])
    svg = f'''
<svg viewBox="{VB}" role="img" aria-label="Predicted RSA from 10 seconds before to 10 seconds after a preschooler starts a regulation strategy: a U shape for distraction, help-seeking, and venting." data-scrub data-x0="{X0}" data-x1="{X1}" data-y0="{Y0}" data-y1="{Y1}" {" ".join(scrub)}>
  {"".join(axes("seconds from the start of a strategy", "RSA"))}
  {xt}
  <line class="onset" x1="{n1(xp(0))}" y1="{Y0 - 6}" x2="{n1(xp(0))}" y2="{Y1}"/>
  <text class="onset-t" x="{n1(xp(0) + 5)}" y="{Y0 + 4}">strategy starts</text>
  {"".join(groups)}
  <rect class="hit" x="{X0}" y="{Y0}" width="{n1(xp(0) - X0)}" height="{Y1 - Y0}" data-explain="<b>Before the strategy:</b> RSA falls in the seconds before the child acts, a response to the challenge."/>
  <rect class="hit" x="{n1(xp(0))}" y="{Y0}" width="{n1(X1 - xp(0))}" height="{Y1 - Y0}" data-explain="<b>After the strategy starts:</b> the fall stops and RSA recovers, the pattern usually read as adaptive regulation."/>
  <circle class="scrub-dot" r="4.5" cx="-20" cy="-20"/>
  <text class="scrub-txt" x="{X1}" y="{Y0 + 4}" text-anchor="end"></text>
</svg>'''

    panel_a = f'''
<div class="ifig-panel">
  <p class="ifig-sub"><span class="term" data-explain="<b>Respiratory sinus arrhythmia (RSA):</b> the variability in heart rate that occurs at the frequency of breathing, controlled by the vagus nerve (Porges, 1995). It is used as an index of the physiological regulation of emotion.">RSA</span> around the start of a strategy</p>
  <div class="ifig-btns" role="group" aria-label="Strategy">
    <button type="button" data-group="strat" data-state="distraction" aria-pressed="true" data-explain="<b>Distraction:</b> a shallow dip in the seconds before the child turned away from the frustration, then a clear rise once distraction began.">Distraction</button>
    <button type="button" data-group="strat" data-state="help" aria-pressed="false" data-explain="<b>Help-seeking:</b> RSA fell steeply over the 10 seconds before the child asked for help, then leveled off and began to recover.">Help-seeking</button>
    <button type="button" data-group="strat" data-state="venting" aria-pressed="false" data-explain="<b>Venting:</b> the same U shape, even though venting is usually called a maladaptive strategy.">Venting</button>
  </div>
  {svg}
  <p class="ifig-src">Predicted RSA for 63 children aged 2 to 6 in a frustration task. Source: {cite("icd2025", "Tang et al., 2025, <i>Infant and Child Development</i>")}.</p>
</div>'''

    # Panel B: polyregulation, composite only (Child Development 2026):
    # a descriptive view, an age view, and an outcome view.
    cd = D["cd2026"]

    # View 1, descriptive: how many of the three strategies children used.
    ymax = 50.0

    def ypc(v):
        return Y1 - v / ymax * (Y1 - Y0)

    bw = 42
    step = (X1 - X0) / 4
    desc_exp = {0: "<b>No strategy:</b> 7% of children used none of the three strategies.",
                1: "<b>One strategy:</b> 11% relied on a single strategy.",
                2: "<b>Two strategies:</b> 44% of children used two strategies.",
                3: "<b>Three strategies:</b> 39% used all three: distraction, help-seeking, and self-speech."}
    bars = []
    for i, (k, pct) in enumerate(cd["strategies_used"]["pct"]):
        cx = X0 + step * (i + 0.5)
        top = ypc(pct)
        bars.append(f'<g class="bar-g" tabindex="0" data-explain="{desc_exp[k]}">'
                    f'<rect class="bar {"poly" if k >= 2 else "mono"}" x="{n1(cx - bw / 2)}" y="{n1(top)}" width="{bw}" height="{n1(Y1 - top)}" rx="5"/>'
                    f'<text class="val" x="{n1(cx)}" y="{n1(top - 5)}" text-anchor="middle">{pct}%</text>'
                    f'<text x="{n1(cx)}" y="{Y1 + 14}" text-anchor="middle">{k}</text></g>')
    bx0, bx1 = X0 + step * 2 + 6, X0 + step * 4 - 6
    by = ypc(44) - 22
    desc = (f'<g class="s-g p-desc">{"".join(ytick(ypc(v), f"{v:.0f}%") for v in [0, 20, 40])}'
            f'{"".join(axes("number of strategies used", "share of children"))}{"".join(bars)}'
            f'<path class="brace" d="M{n1(bx0)},{n1(by + 6)} L{n1(bx0)},{n1(by)} L{n1(bx1)},{n1(by)} L{n1(bx1)},{n1(by + 6)}"/>'
            f'<text class="brace-t" x="{n1((bx0 + bx1) / 2)}" y="{n1(by - 6)}" text-anchor="middle">83% used more than one</text></g>')

    # View 2, age: composite mean and SD by age group (Table 2).
    lo2, hi2 = -1.5, 1.6

    def ya(v):
        return Y1 - (v - lo2) / (hi2 - lo2) * (Y1 - Y0)

    pts, means = [], []
    for i, g in enumerate(cd["composite_by_age"]["groups"]):
        cx = X0 + step * (i + 0.5)
        means.append((cx, ya(g["m"])))
        exp = f'<b>Age {g["age"]}</b> (n = {g["n"]}): mean {fmt(g["m"])}, SD {g["sd"]:.2f} on the composite.'
        pts.append(f'<g class="pt-g" tabindex="0" data-explain="{exp}">'
                   f'<line class="whisk" x1="{n1(cx)}" y1="{n1(ya(g["m"] + g["sd"]))}" x2="{n1(cx)}" y2="{n1(ya(g["m"] - g["sd"]))}"/>'
                   f'<circle class="mean" cx="{n1(cx)}" cy="{n1(ya(g["m"]))}" r="6"/>'
                   f'<text x="{n1(cx)}" y="{Y1 + 14}" text-anchor="middle">{g["age"]}</text>'
                   f'<text class="pct" x="{n1(cx)}" y="{Y1 + 26}" text-anchor="middle">n = {g["n"]}</text></g>')
    age_view = (f'<g class="s-g p-age">{"".join(ytick(ya(v), fmt(v, 0)) for v in [-1, 0, 1])}'
           f'{"".join(axes(None, "polyregulation (composite)"))}'
           f'<path class="trend" d="{path(means)}"/>{"".join(pts)}'
           f'<text class="ax-t" x="{X1}" y="226" text-anchor="end">age (years)</text></g>')

    # View 3, outcome: a fan of model-implied lines, one per age from 2 to 6,
    # from the estimates reported in the paper. Solid lines are ages outside
    # the Johnson-Neyman bounds, where the link was significant.
    G2 = cd["indices"]["poly"]
    oc = cd["composite_outcome"]
    gx0 = min(g["x0"] for g in G2["groups"].values())
    gx1 = max(g["x1"] for g in G2["groups"].values())
    lo3, hi3 = -2.0, 2.0

    def xo(v):
        return X0 + (v - gx0) / (gx1 - gx0) * (X1 - X0)

    def yo(v):
        return Y1 - (v - lo3) / (hi3 - lo3) * (Y1 - Y0)

    a_lo, a_hi = oc["mean_age"] - oc["sd_age"], oc["mean_age"] + oc["sd_age"]
    k_age = (oc["older_b"] - oc["younger_b"]) / (a_hi - a_lo)

    def slope(age):
        return oc["younger_b"] + k_age * (age - a_lo)

    def pred(age, x):
        return oc["age_b"] * (age - oc["mean_age"]) + slope(age) * x

    ages = [2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0]
    fan_col = ["#2f6f80", "#437b8e", "#6f9fae", "#9bb5bf", "#bcbcb4", "#e2b27c", "#eda25a", "#e0851c", "#c26b0f"]
    lines_f, hits_f = [], []
    for age, col in zip(ages, fan_col):
        sgn = age < oc["jn_below"] or age > oc["jn_above"]
        d_ = f"M{n1(xo(gx0))},{n1(yo(pred(age, gx0)))} L{n1(xo(gx1))},{n1(yo(pred(age, gx1)))}"
        lines_f.append(f'<path class="fan {"sig" if sgn else "ns"}" d="{d_}" style="stroke:{col}"/>')
        if sgn:
            word = "less" if slope(age) < 0 else "more"
            note = f"significant: more polyregulation, {word} negative affect"
        else:
            note = "not significant at this age"
        hits_f.append(f'<path class="hitline" d="{d_}" data-explain="<b>Age {age:g}:</b> slope {fmt(slope(age))}, {note}."/>')
    keyx = X1 - 128
    key = "".join(f'<line x1="{keyx + i * 10}" y1="0" x2="{keyx + i * 10 + 8}" y2="0" style="stroke:{c};stroke-width:3"/>' for i, c in enumerate(fan_col))
    xt = "".join(xtick(xo(v), fmt(v, 2)) for v in G2["xticks"])
    out = (f'<g class="s-g p-out">{"".join(ytick(yo(v), fmt(v, 0)) for v in [-2, -1, 0, 1, 2])}'
           f'{"".join(axes(None, "negative affect"))}{"".join(lines_f)}{"".join(hits_f)}{xt}'
           f'<text class="ax-t" x="{X1}" y="226" text-anchor="end">polyregulation (composite)</text>'
           f'<g class="key" transform="translate(0,{Y0 - 16})">{key}'
           f'<text x="{keyx - 4}" y="3.5" text-anchor="end">age 2</text><text x="{keyx + 92}" y="3.5">6</text></g>'
           f'<text class="fan-note" x="{X1}" y="{Y1 - 6}" text-anchor="end">solid: significant</text></g>')

    svg_b = f"""
<svg viewBox="{VB}" role="img" aria-label="Polyregulation in preschoolers: most used more than one strategy; younger children used more polyregulation; polyregulation went with less negative affect in the youngest children and more in the oldest.">
  <defs><clipPath id="clip-poly"><rect x="{X0}" y="{Y0 - 6}" width="{X1 - X0}" height="{Y1 - Y0 + 6}"/></clipPath></defs>
  {desc}{age_view}{out}
</svg>"""

    panel_b = f"""
<div class="ifig-panel">
  <p class="ifig-sub"><span class="term" data-explain="<b>Emotion polyregulation:</b> the use of multiple emotion regulation strategies within a single emotional episode (Ford et al., 2019). The composite averages three indicators: variety (how many strategies a child used), switching (how often the child changed strategy), and diversity (how evenly the strategies were used).">Polyregulation</span> in preschoolers</p>
  <div class="ifig-btns" role="group" aria-label="View">
    <button type="button" data-group="poly" data-state="desc" aria-pressed="true" data-explain="<b>Descriptive:</b> most preschoolers (83%) used more than one strategy during the frustration task: 44% used two and 39% used three.">Descriptive</button>
    <button type="button" data-group="poly" data-state="age" aria-pressed="false" data-explain="<b>Age:</b> younger children used more polyregulation, and 2-year-olds the most. The composite differed across age groups (Kruskal–Wallis χ²(3) = 19.23, p &lt; .001).">Age</button>
    <button type="button" data-group="poly" data-state="out" aria-pressed="false" data-explain="<b>Outcome:</b> each line shows the link between polyregulation and negative affect at one age, from 2 to 6. The link depended on age (b = 0.40, p = .007). Solid lines mark ages where it was significant by the Johnson–Neyman technique: below 2.70 years, more polyregulation went with less negative affect; above 5.27 years, with more.">Outcome</button>
  </div>
  {svg_b}
  <p class="ifig-src">57 children aged 2 to 6 in a locked-box frustration task. Negative affect combines global frustration, venting frequency, and venting duration; the age lines are computed from the reported estimates. Source: {cite("cd2026", "Tang et al., 2026, <i>Child Development</i>")}.</p>
</div>"""

    html = f"""
<figure class="ifig" data-strat="distraction" data-poly="desc">
  <figcaption class="ifig-head"><span class="ifig-title">Regulation as it unfolds</span></figcaption>
  <div class="ifig-grid">{panel_a}{panel_b}</div>
  <p class="ifig-explain" aria-live="polite">Point at any part of a plot, or use the buttons, to see what it shows.</p>
</figure>"""
    write("fig-unfold.md", html)


# ---------------------------------------------------------------------------
# Figure 2. Coping and resources under stress
# ---------------------------------------------------------------------------
def fig_stress():
    # Panel A, state "day": diary, schematic of an unpublished finding.
    day = f'''<g class="s-g c-day">
    {"".join(axes("more coping effort than usual", "next-day negative affect"))}
    <path class="line red" d="M{X0 + 12},{Y0 + 26} L{X1 - 12},{Y1 - 34}"/>
    <path class="line grey" d="M{X0 + 12},{(Y0 + Y1) / 2 + 8} L{X1 - 12},{(Y0 + Y1) / 2 + 8}"/>
    <text class="lab-red" x="{X0 + 16}" y="{Y0 + 16}">days with moderate or severe stress</text>
    <text x="{X0 + 16}" y="{(Y0 + Y1) / 2 + 24}">days with little or no stress</text>
    <path class="hitline" d="M{X0 + 12},{Y0 + 26} L{X1 - 12},{Y1 - 34}" data-explain="<b>On days with moderate or severe stress,</b> more coping effort than usual predicted less negative affect the next day."/>
    <path class="hitline" d="M{X0 + 12},{(Y0 + Y1) / 2 + 8} L{X1 - 12},{(Y0 + Y1) / 2 + 8}" data-explain="<b>On days with little or no stress,</b> extra coping effort made no difference the next day."/>
  </g>'''

    # Panel A, state "year": coping flexibility, an unpublished finding drawn as
    # a shape in relative units (0 to 1 on both axes), with no model numbers:
    # the stress-health link is weakest at moderate flexibility.
    f0, f1 = 0.0, 1.0
    f_min, z_lo, z_hi = 0.482, 0.369, 0.604

    def xf(v):
        return X0 + (v - f0) / (f1 - f0) * (X1 - X0)

    def yh(h):
        return Y1 - h / 1.0 * (Y1 - Y0)

    def harm(v):
        return 0.05 + 3.25 * (v - f_min) ** 2

    curve = [(xf(v), yh(harm(v))) for v in frange(f0, f1, 60)]
    year = f'''<g class="s-g c-year">
    <rect class="zone" x="{X0}" y="{Y0}" width="{n1(xf(z_lo) - X0)}" height="{Y1 - Y0}" data-explain="<b>Coping that barely shifted</b> as daily stress changed: here, chronic stress clearly predicted poorer physical health a year later."/>
    <rect class="zone" x="{n1(xf(z_hi))}" y="{Y0}" width="{n1(X1 - xf(z_hi))}" height="{Y1 - Y0}" data-explain="<b>Coping that shifted very strongly</b> with each change in stress: the link between chronic stress and poorer health returned."/>
    <rect class="hit" x="{n1(xf(z_lo))}" y="{Y0}" width="{n1(xf(z_hi) - xf(z_lo))}" height="{Y1 - Y0}" data-explain="<b>Moderate flexibility:</b> the link between chronic stress and later health weakened to near zero."/>
    {"".join(axes("how much coping shifted as daily stress changed", "chronic stress → poorer health a year later"))}
    <text x="{X0 + 2}" y="{Y1 + 14}">little</text>
    <text x="{X1}" y="{Y1 + 14}" text-anchor="end">very strongly</text>
    <text class="zone-t" x="{n1((xf(z_lo) + xf(z_hi)) / 2)}" y="{Y0 + 14}" text-anchor="middle">link weakens</text>
    <path class="line amber u-curve" d="{path(curve)}"/>
    <circle class="u-dot" r="6.5" cx="{n1(xf(f_min))}" cy="{n1(yh(harm(f_min)))}"/>
  </g>'''

    panel_a = f'''
<div class="ifig-panel">
  <p class="ifig-sub"><span class="term" data-explain="<b>Coping:</b> conscious, volitional efforts to regulate emotion, cognition, behavior, physiology, and the environment in response to stressful events or circumstances (Compas et al., 2001).">Coping</span> that fits the stress</p>
  <div class="ifig-btns" role="group" aria-label="Timescale">
    <button type="button" data-group="cope" data-state="day" aria-pressed="true" data-explain="<b>Day to day:</b> in a 14-day diary, more coping effort than usual predicted less negative affect the next day after days with moderate or severe stress, but not after days with little or no stress.">Day to day</button>
    <button type="button" data-group="cope" data-state="year" aria-pressed="false" data-explain="<b>Coping flexibility:</b> the capacity to adjust coping as demands shift (Bonanno &amp; Burton, 2013), here measured as how much adolescents’ daily coping changed with daily stress over 14 days. Chronic stress predicted poorer physical health a year later when coping shifted very little or very strongly. Drag the slider.">Over a year</button>
  </div>
  <svg viewBox="{VB}" role="img" aria-label="Coping that fits the stress: day-to-day diary pattern, and a U-shaped link between coping flexibility and the harm of chronic stress.">{day}{year}</svg>
  <input class="ifig-range s-g c-year" type="range" min="0" max="100" value="50" aria-label="Coping flexibility"
    data-low="<b>Coping shifted little</b> as daily stress changed: chronic stress predicted poorer physical health a year later."
    data-mid="<b>Moderate flexibility:</b> the link between chronic stress and later health weakened to near zero."
    data-high="<b>Coping shifted very strongly:</b> the link returned.">
  <p class="ifig-src s-g c-day">Schematic of an unpublished diary finding (in preparation).</p>
  <p class="ifig-src s-g c-year">Shape of an unpublished finding, drawn without numbers (submitted to SRCD).</p>
</div>'''

    # Panel B, state "family": Current Psychology 2023 (real values).
    cp = D["cp2023"]
    order = ["cohesive", "mild", "indifferent", "conflictual"]
    P = {p["key"]: p for p in cp["profiles"]}
    lo, hi = 1.0, 3.2

    def yv(v):
        return Y1 - (v - lo) / (hi - lo) * (Y1 - Y0)

    desc = {
        "cohesive": "warm, low-conflict relationships with parents and siblings, with conflict rising slightly during the lockdown",
        "mild": "moderate warmth, with conflict rising during the lockdown",
        "indifferent": "the least warmth with parents and siblings, and high conflict, unchanged by the lockdown",
        "conflictual": "high conflict with parents and the most conflict with siblings, before and during the lockdown",
    }
    fills = {"cohesive": "#5f9fb4", "mild": "#b3c8e0", "indifferent": "#fc9833", "conflictual": "#ee9879"}
    bars = []
    bw, gap = 44, 20
    start = X0 + 16
    for i, k in enumerate(order):
        p = P[k]
        x = start + i * (bw + gap)
        top = yv(p["emo"])
        e1, e2 = yv(p["emo"] + p["emo_se"]), yv(p["emo"] - p["emo_se"])
        label = p["name"].split("-")
        exp = (f'<b>{p["name"]}</b> ({p["pct"]:.0f}% of adolescents): {desc[k]}. '
               f'Emotional responses (panic, loneliness, anxiety, depression, anger): {p["emo"]:.2f} on a 1 to 5 scale.')
        bars.append(
            f'<g class="bar-g" tabindex="0" data-explain="{exp}">'
            f'<rect class="bar" x="{x}" y="{n1(top)}" width="{bw}" height="{n1(Y1 - top)}" rx="5" style="fill:{fills[k]}"/>'
            f'<line class="whisk" x1="{x + bw / 2}" y1="{n1(e1)}" x2="{x + bw / 2}" y2="{n1(e2)}"/>'
            f'<text class="val" x="{x + bw / 2}" y="{n1(e1 - 5)}" text-anchor="middle">{p["emo"]:.2f}</text>'
            f'<text x="{x + bw / 2}" y="{Y1 + 13}" text-anchor="middle">{label[0]}-</text>'
            f'<text x="{x + bw / 2}" y="{Y1 + 24}" text-anchor="middle">{label[1]}</text>'
            f'<text class="pct" x="{x + bw / 2}" y="{Y1 + 36}" text-anchor="middle">{p["pct"]:.0f}%</text>'
            f'</g>')
    yt = "".join(ytick(yv(v), str(v)) for v in [1, 2, 3])
    family = f'''<g class="s-g r-family">
    {yt}
    {"".join(axes(None, "emotional responses during the lockdown (1 to 5)"))}
    {"".join(bars)}
  </g>'''

    # Panel B, state "resilience": a fan of resilience levels for peer or
    # institutional discrimination; a schematic of an unpublished finding.
    xa, xb = X0 + 8, X1 - 70
    ylo_r, yhi_r = Y1 - 18, Y0 + 22

    def ry(f):
        return ylo_r + (yhi_r - ylo_r) * f

    ends = {"peer": {"low": (0.10, 0.92), "high": (0.02, 0.80)},
            "inst": {"low": (0.10, 0.88), "high": (0.06, 0.12)}}
    res_col = ["#c2553c", "#d98a6f", "#b9bec8", "#6f9fae", "#2f6f80"]
    rexp = {
        "peer": {0: "<b>Peer discrimination, low resilience:</b> more discrimination, larger swings in negative affect.",
                 4: "<b>Peer discrimination, high resilience:</b> larger swings as well. Resilience did not change this link."},
        "inst": {0: "<b>Institutional discrimination, low resilience:</b> more discrimination, larger swings in negative affect.",
                 4: "<b>Institutional discrimination, high resilience:</b> no link with swings in negative affect."},
    }
    rg = []
    for k in ["peer", "inst"]:
        lo_, hi_ = ends[k]["low"], ends[k]["high"]
        parts = []
        for i, col in enumerate(res_col):
            w = i / 4
            f0 = lo_[0] + (hi_[0] - lo_[0]) * w
            f1 = lo_[1] + (hi_[1] - lo_[1]) * w
            d_ = f"M{xa},{n1(ry(f0))} L{xb},{n1(ry(f1))}"
            parts.append(f'<path class="fan sig" d="{d_}" style="stroke:{col}"/>')
            if i in rexp[k]:
                parts.append(f'<path class="hitline" d="{d_}" data-explain="{rexp[k][i]}"/>')
                lab = "low resilience" if i == 0 else "high resilience"
                parts.append(f'<text class="end-l" x="{xb + 6}" y="{n1(ry(f1) + 3.5)}" style="fill:{col}">{lab}</text>')
        rg.append(f'<g class="s-g q-{k}">{"".join(parts)}</g>')
    res = f"""<g class="s-g r-res">
    {"".join(axes("more discrimination", "swings in negative affect"))}
    {"".join(rg)}
  </g>"""

    panel_b = f'''
<div class="ifig-panel">
  <p class="ifig-sub"><span class="term" data-explain="<b>Regulatory resources:</b> what adolescents can draw on to regulate under stress, within themselves (such as resilience) and around them (such as family relationships).">Resources</span></p>
  <div class="ifig-btns" role="group" aria-label="Resource">
    <button type="button" data-group="res" data-state="family" aria-pressed="true" data-explain="<b>Family relationship profiles:</b> latent profiles of parent–adolescent and sibling warmth and conflict before and during the COVID-19 pandemic. Adolescents in the conflictual profile reported the most emotional responses; those in the cohesive profile reported the least.">Family</button>
    <button type="button" data-group="res" data-state="res" aria-pressed="false" data-explain="<b>Resilience:</b> peer-perpetrated discrimination was linked to larger swings in negative affect regardless of adolescents’ resilience; institutional discrimination was linked to larger swings only among adolescents low in resilience.">Resilience</button>
  </div>
  <div class="ifig-btns ifig-btns-sub s-g r-res" role="group" aria-label="Source of discrimination">
    <button type="button" data-group="disc" data-state="peer" aria-pressed="true" data-explain="<b>Peer-perpetrated discrimination:</b> racial or ethnic discrimination from peers. <b>Swings in negative affect</b> (instability): the size and frequency of day-to-day changes in negative affect over the 14-day diary.">From peers</button>
    <button type="button" data-group="disc" data-state="inst" aria-pressed="false" data-explain="<b>Institutional discrimination:</b> racial or ethnic discrimination from societal institutions. <b>Swings in negative affect</b> (instability): the size and frequency of day-to-day changes in negative affect over the 14-day diary.">From institutions</button>
  </div>
  <svg viewBox="0 0 320 250" role="img" aria-label="Distress during the COVID-19 lockdown by family relationship profile, lowest for cohesive families and highest for conflictual ones; and a schematic of resilience buffering institutional but not peer discrimination.">{family}{res}</svg>
  <p class="ifig-src s-g r-family">2,305 adolescents aged 10 to 18 in China; means with standard errors. Source: {cite("cp2023", "Tang et al., 2023, <i>Current Psychology</i>")}.</p>
  <p class="ifig-src s-g r-res">Schematic of an unpublished finding (in preparation).</p>
</div>'''

    html = f'''
<figure class="ifig" data-cope="day" data-res="family" data-disc="peer">
  <figcaption class="ifig-head"><span class="ifig-title">Coping and resources under stress</span></figcaption>
  <div class="ifig-grid">{panel_a}{panel_b}</div>
  <p class="ifig-explain" aria-live="polite">Whether stress harms adolescents’ health depends on how they cope and on the resources they have. Coping works best when it fits the stress.</p>
</figure>'''
    write("fig-stress.md", html)


# ---------------------------------------------------------------------------
# Figure 3. Same synchrony, different meaning
# ---------------------------------------------------------------------------
def fig_synchrony():
    # Left: how synchrony was measured (her paper's analytic model, drawn as epochs).
    xs = [92 + i * 30 for i in range(8)]
    yg, yc = 72, 152
    eg = "".join(f'<circle class="ep g" cx="{x}" cy="{yg}" r="8.5"/>' for x in xs)
    ec = "".join(f'<circle class="ep c" cx="{x}" cy="{yc}" r="8.5"/>' for x in xs)
    lag = "".join(f'<path class="arrow" d="M{xs[i] + 4},{yg + 9} L{xs[i + 1] - 4},{yc - 11}" marker-end="url(#arr)"/>' for i in range(7))
    con = "".join(f'<path class="arrow" d="M{x},{yg + 10} L{x},{yc - 12}" marker-end="url(#arr)"/>' for x in xs)
    ticks = "".join(f'<text x="{x}" y="{yc + 26}" text-anchor="middle">{i + 1}</text>' for i, x in enumerate(xs))
    left = f'''
<div class="ifig-panel">
  <p class="ifig-sub"><span class="term" data-explain="<b>Physiological synchrony:</b> the extent to which changes in caregivers’ and children’s physiological responses correspond with one another (Miller et al., 2023).">Synchrony</span>, epoch by epoch</p>
  <div class="ifig-btns" role="group" aria-label="Task">
    <button type="button" data-group="task" data-state="draw" aria-pressed="true" data-explain="<b>Drawing together</b> (a house and a tree on an Etch-A-Sketch): when the child’s RSA followed the grandmother’s RSA 30 seconds later, the child reported better anger regulation.">Drawing together</button>
    <button type="button" data-group="task" data-state="conflict" aria-pressed="false" data-explain="<b>Conflict discussion:</b> when the child’s RSA moved with the grandmother’s at the same moment, the child reported poorer anger regulation.">Conflict discussion</button>
  </div>
  <svg viewBox="{VB}" role="img" aria-label="Eight 30-second epochs for grandmother and grandchild. In the drawing task, arrows run from the grandmother in one epoch to the child in the next; in the conflict discussion, from the grandmother to the child in the same epoch.">
    <defs><marker id="arr" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0 L8,4 L0,8 Z" class="arr-head"/></marker></defs>
    <text class="lane" x="{xs[0] - 16}" y="{yg + 4}" text-anchor="end">grandmother</text>
    <text class="lane" x="{xs[0] - 16}" y="{yc + 4}" text-anchor="end">grandchild</text>
    <g class="s-g t-draw">{lag}<path class="hitline" d="M{xs[0]},{yg} L{xs[-1]},{yc}" data-explain="<b>Lagged synchrony:</b> the grandmother’s RSA in one 30-second epoch predicting the child’s RSA in the next epoch."/>
      <text class="mode" x="{xs[0]}" y="{yg - 18}">next 30 seconds: lagged</text></g>
    <g class="s-g t-conflict">{con}<path class="hitline" d="M{xs[0]},{(yg + yc) / 2} L{xs[-1]},{(yg + yc) / 2}" data-explain="<b>Concurrent synchrony:</b> the grandmother’s RSA predicting the child’s RSA in the same 30-second epoch."/>
      <text class="mode" x="{xs[0]}" y="{yg - 18}">same 30 seconds: concurrent</text></g>
    {eg}{ec}
    {ticks}
    <text class="ax-t" x="{xs[-1] + 8}" y="{yc + 42}" text-anchor="end">eight 30-second epochs, about 4 minutes</text>
  </svg>
  <p class="ifig-src">RSA in 30-second epochs, as in the paper’s analytic model.</p>
</div>'''

    # Right: what it meant for the child (Developmental Psychobiology 2024,
    # Figure 2): the fitted slope and its band; the pairs' dots are left out.
    dp = D["dp2024"]["panels"]
    ylo, yhi = 0.85, 3.15

    def yv(v):
        return Y1 - (v - ylo) / (yhi - ylo) * (Y1 - Y0)

    groups = []
    for key, d in dp.items():
        task, outc = d["task"], d["outcome"]
        a, b = d["x0"], d["x1"]

        def xv(v, a=a, b=b):
            return X0 + 6 + (v - a) / (b - a) * (X1 - X0 - 12)

        xs_ = frange(a, b, 40)
        mid = [d["b0"] + d["b1"] * x for x in xs_]
        hw = [math.sqrt(max(0.0, d["hw2"][0] * x * x + d["hw2"][1] * x + d["hw2"][2])) for x in xs_]
        band = path([(xv(x), yv(m + h)) for x, m, h in zip(xs_, mid, hw)] +
                    [(xv(x), yv(m - h)) for x, m, h in zip(xs_, mid, hw)][::-1]) + " Z"
        line = path([(xv(a), yv(mid[0])), (xv(b), yv(mid[-1]))])
        xt = "".join(xtick(xv(v), fmt(v, 2 if task == "conflict" else 1)) for v in d["xticks"])
        word = "better" if task == "draw" else "poorer"
        o = "anger coping" if outc == "coping" else "anger inhibition"
        exp = (f"<b>Fitted slope with its confidence band:</b> more synchrony, {word} {o}.")
        xlab = "lagged synchrony (child follows 30 s later)" if task == "draw" else "concurrent synchrony (same 30 s)"
        groups.append(f'<g class="s-g d-{task}-{outc}"><path class="band ink" d="{band}" clip-path="url(#clip-dp)"/>'
                      f'<path class="line blue" d="{line}"/><path class="hitline" d="{line}" data-explain="{exp}"/>{xt}'
                      f'<text class="ax-t" x="{X1}" y="226" text-anchor="end">{xlab}</text></g>')
    yt = "".join(ytick(yv(v), f"{v:.1f}") for v in [1.0, 1.5, 2.0, 2.5, 3.0])
    right = f"""
<div class="ifig-panel">
  <p class="ifig-sub">Synchrony and the child’s anger regulation</p>
  <div class="ifig-btns" role="group" aria-label="Outcome">
    <button type="button" data-group="out" data-state="coping" aria-pressed="true" data-explain="<b>Anger coping:</b> a subscale of the Children’s Emotion Management Scales (Zeman et al., 2001): constructive ways of managing anger, child report, 1 to 3.">Anger coping</button>
    <button type="button" data-group="out" data-state="inhibition" aria-pressed="false" data-explain="<b>Anger inhibition:</b> a subscale of the Children’s Emotion Management Scales (Zeman et al., 2001): suppressing the expression of anger, child report, 1 to 3.">Anger inhibition</button>
  </div>
  <svg viewBox="{VB}" role="img" aria-label="Fitted lines: during drawing, lagged synchrony goes with more anger coping; during conflict, concurrent synchrony goes with less.">
    <defs><clipPath id="clip-dp"><rect x="{X0}" y="{Y0 - 6}" width="{X1 - X0}" height="{Y1 - Y0 + 6}"/></clipPath></defs>
    {yt}
    {"".join(axes(None, "child’s anger regulation (1 to 3)"))}
    {"".join(groups)}
  </svg>
  <p class="ifig-src">92 grandmother–grandchild pairs in urban China, children aged 8 to 10. Source: {cite("dp2024", "Tang et al., 2024, <i>Developmental Psychobiology</i>")}.</p>
</div>"""

    html = f'''
<figure class="ifig" data-task="draw" data-out="coping">
  <figcaption class="ifig-head"><span class="ifig-title">Same synchrony, different meaning</span></figcaption>
  <div class="ifig-grid">{left}{right}</div>
  <p class="ifig-explain" aria-live="polite">Grandmothers and grandchildren drew together and then discussed a disagreement while their RSA was recorded. The same physiological link went with better anger regulation in one task and poorer in the other.</p>
</figure>'''
    write("fig-synchrony.md", html)


# ---------------------------------------------------------------------------
# Figure 4. Levels of the family system, as a network
# ---------------------------------------------------------------------------
def fig_network():
    R = D["rcap2023"]
    s = 0.42
    ox, oy = 40, 28
    # Label side for each node: right of the circle unless that collides.
    side = {6: "left", 3: "left", 17: "left", 16: "left", 21: "below", 19: "above"}

    def P(n):
        return ox + (n["x"] - 89) * s, oy + (n["y"] - 104) * s

    nodes = {n["id"]: n for n in R["nodes"]}
    pos = {k: P(n) for k, n in nodes.items()}
    level_name = {"sym": "symptom of oppositional defiant disorder", "sys": "family-system level", "dya": "dyadic level", "ind": "individual level", "cov": "covariate"}
    sym_text = {1: "often loses temper", 2: "often argues with adults", 3: "often refuses to follow adults’ requests or rules", 4: "often deliberately annoys others",
                5: "often blames others for their own mistakes", 6: "often touchy or easily annoyed", 7: "often angry and resentful", 8: "often spiteful or vindictive"}
    extra = {11: " The family-system factor most closely tied to children’s symptoms.", 15: " The dyadic factor most closely tied to children’s symptoms.",
             18: " The individual-level factor most closely tied to children’s symptoms.", 4: " The most central symptom, and a main bridge to family factors.",
             8: " A main bridge between symptoms and family factors."}
    key_nodes = {11, 15, 18, 4, 8}

    edges = []
    for e in sorted(R["edges"], key=lambda e: e["w"]):
        (x1, y1), (x2, y2) = pos[e["a"]], pos[e["b"]]
        la, lb = nodes[e["a"]]["level"], nodes[e["b"]]["level"]
        w = e["w"]
        edges.append(f'<line class="e lv-{la} lv-{lb}" data-a="{e["a"]}" data-b="{e["b"]}" x1="{n1(x1)}" y1="{n1(y1)}" x2="{n1(x2)}" y2="{n1(y2)}" '
                     f'style="stroke-width:{0.6 + 3.2 * w:.2f};stroke-opacity:{0.1 + 0.62 * w:.2f}"/>')
    circles, labels = [], []
    for k, n in sorted(nodes.items()):
        x, y = pos[k]
        name = n["name"]
        if n["level"] == "sym":
            exp = f"<b>{name}</b>: {sym_text[k]}. A {level_name['sym']}.{extra.get(k, '')}"
        else:
            exp = f"<b>{name}</b> · {level_name[n['level']]}.{extra.get(k, '')}"
        cls = f"nd lv-{n['level']}" + (" key" if k in key_nodes else "")
        circles.append(f'<circle class="{cls}" data-id="{k}" cx="{n1(x)}" cy="{n1(y)}" r="11" data-explain="{exp}"/>')
        where = side.get(k, "right")
        if where == "below":
            lx, ly, anchor = x, y + 24, "middle"
        elif where == "above":
            lx, ly, anchor = x, y - 16, "middle"
        elif where == "left":
            lx, ly, anchor = x - 15, y + 3.5, "end"
        else:
            lx, ly, anchor = x + 15, y + 3.5, "start"
        labels.append(f'<text class="nl lv-{n["level"]}" data-id="{k}" x="{n1(lx)}" y="{n1(ly)}" text-anchor="{anchor}">{name}</text>')

    legend = ('<g class="net-key" transform="translate(40,458)">'
              '<circle class="nd lv-sym" cx="0" cy="0" r="6"/><text x="10" y="3.5">ODD symptoms</text>'
              '<circle class="nd lv-sys" cx="112" cy="0" r="6"/><text x="122" y="3.5">family system</text>'
              '<circle class="nd lv-dya" cx="222" cy="0" r="6"/><text x="232" y="3.5">dyads</text>'
              '<circle class="nd lv-ind" cx="292" cy="0" r="6"/><text x="302" y="3.5">individuals</text>'
              '<circle class="nd lv-cov" cx="384" cy="0" r="6"/><text x="394" y="3.5">covariates</text>'
              '<circle class="nd key" cx="480" cy="0" r="6"/><text x="490" y="3.5">central or bridging</text></g>')

    html = f'''
<figure class="ifig ifig-net" data-level="all">
  <figcaption class="ifig-head"><span class="ifig-title">Levels of the family system, as a network</span></figcaption>
  <p class="ifig-sub"><span class="term" data-explain="<b>Oppositional defiant disorder (ODD):</b> recurrent negativistic, defiant, disobedient, and hostile behavior toward authority figures that persists for at least six months.">ODD symptoms</span> and family factors</p>
  <div class="ifig-btns" role="group" aria-label="Level">
    <button type="button" data-group="level" data-state="all" aria-pressed="true" data-explain="Symptoms of oppositional defiant disorder (ODD) and family factors at three levels. Lines are associations; darker lines are stronger.">Everything</button>
    <button type="button" data-group="level" data-state="sys" aria-pressed="false" data-explain="<b>Family system:</b> family cohesion was the factor most closely tied to children’s symptoms.">Family system</button>
    <button type="button" data-group="level" data-state="dya" aria-pressed="false" data-explain="<b>Dyads:</b> parent–child conflict was the key factor among relationships within the family.">Dyads</button>
    <button type="button" data-group="level" data-state="ind" aria-pressed="false" data-explain="<b>Individuals:</b> parental depression was the key factor among individual family members’ characteristics.">Individuals</button>
    <button type="button" data-group="level" data-state="sym" aria-pressed="false" data-explain="<b>Symptoms:</b> “annoys others on purpose” was the most central symptom; it and “vindictive” were the main bridges to family factors.">Symptoms</button>
  </div>
  <div class="net-wrap"><svg class="net" viewBox="0 0 640 470" role="img" aria-label="Network of eight ODD symptoms and fifteen family factors. Family cohesion, parent–child conflict, and parental depression are the most connected family factors.">
    <g class="edges">{"".join(edges)}</g>
    <g class="nodes">{"".join(circles)}</g>
    <g class="labels">{"".join(labels)}</g>
    {legend}
  </svg></div>
  <p class="ifig-src">718 migrant children aged 7 to 14 in Beijing. Node positions and line darkness follow Figure 2 of the paper. Source: {cite("rcap2023", "Zhang, Tang, et al., 2023, <i>Research on Child and Adolescent Psychopathology</i>")} (co-first author).</p>
  <p class="ifig-explain" aria-live="polite">A child’s difficulties connect to the family at several levels at once. Point at a circle to see what it is and what it connects to.</p>
</figure>'''
    write("fig-network.md", html)


if __name__ == "__main__":
    fig_unfold()
    fig_stress()
    fig_synchrony()
    fig_network()
    print("wrote", ", ".join(sorted(os.listdir(OUT))))
